- name: Create TEMP run dir
  file:
    path: "/var/run/{{ blazar_program_name }}"
    state: directory
    owner: "{{ blazar_system_user_name }}"
    group: "{{ blazar_system_group_name }}"
    mode: "02755"

- name: Create TEMP lock dir
  file:
    path: "/var/lock/{{ blazar_program_name }}"
    state: directory
    owner: "{{ blazar_system_user_name }}"
    group: "{{ blazar_system_group_name }}"
    mode: "02755"

- name: Create tmpfiles.d entry
  template:
    src: "blazar-systemd-tmpfiles.j2"
    dest: "/etc/tmpfiles.d/openstack-{{ blazar_program_name }}.conf"
    mode: "0644"
    owner: "root"
    group: "root"
  notify:
    - Restart blazar services

- name: Place the systemd init script
  config_template:
    src: "blazar-systemd-init.j2"
    dest: "/etc/systemd/system/{{ blazar_program_name }}.service"
    mode: "0644"
    owner: "root"
    group: "root"
    config_type: "ini"
  notify:
    - Restart blazar services
